services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - '5432:5432'

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies-catalog
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
    command: npm run start:dev

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres:
    driver: local
  redisdata:
    driver: local
