services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresdata:/postgres/data
    ports:
      - '5432:5432'

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies-catalog
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src
    command: npm run start:dev

volumes:
  postgresdata:
    driver: local
  redisdata:
    driver: local
